name: arc2face
channels:
  - nvidia
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - accelerate=0.23.0
  - aiofiles=22.1.0
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - albumentations=1.3.1
  - alsa-lib=1.2.8
  - altair=5.0.1
  - annotated-types=0.6.0
  - anyio=4.6.2
  - aom=3.5.0
  - arrow-cpp=14.0.2
  - async-timeout=4.0.3
  - attr=2.5.1
  - attrs=24.2.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - blas=1.0
  - boost-cpp=1.81.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - cairo=1.16.0
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - contourpy=1.2.0
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cuda-version=12.6
  - cycler=0.11.0
  - cython=3.0.11
  - cytoolz=0.12.2
  - dask-core=2024.8.2
  - dataclasses=0.8
  - datasets=2.14.6
  - dbus=1.13.18
  - diffusers=0.23.0
  - dill=0.3.6
  - easydict=1.13
  - exceptiongroup=1.2.0
  - expat=2.6.3
  - fastapi=0.112.2
  - ffmpeg=4.4.2
  - ffmpy=0.3.0
  - fftw=3.3.10
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freeglut=3.2.2
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2023.10.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.9
  - gradio=4.8.0
  - gradio-client=0.7.1
  - graphite2=1.3.14
  - grpc-cpp=1.48.2
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.40
  - h11=0.14.0
  - harfbuzz=5.3.0
  - hdf5=1.12.2
  - httpcore=1.0.2
  - httpx=0.27.0
  - huggingface_hub=0.17.3
  - humanfriendly=10.0
  - icu=70.1
  - idna=3.7
  - imagecodecs-lite=2019.12.3
  - imageio=2.33.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.4.0
  - insightface=0.7.3
  - intel-openmp=2023.1.0
  - jack=1.9.22
  - jasper=2.0.33
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.12
  - ld_impl_linux-64=2.43
  - lerc=3.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.11.1.6
  - libcups=2.3.3
  - libcurand=10.3.7.77
  - libcurl=8.9.1
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdb=6.2.32
  - libdeflate=1.8
  - libdrm=2.4.123
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libglu=9.0.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.57.0
  - libnpp=11.7.4.75
  - libnsl=2.0.1
  - libnvjpeg=11.8.0.2
  - libogg=1.3.5
  - libopencv=4.6.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=3.20.3
  - libsndfile=1.2.2
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=253
  - libtasn1=4.19.0
  - libthrift=0.15.0
  - libtiff=4.4.0
  - libtool=2.4.7
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - locket=1.0.0
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib-base=3.9.2
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpg123=1.32.9
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.14
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.3
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.10.1
  - numpy=1.23.5
  - numpy-base=1.23.5
  - onnx=1.16.0
  - onnxruntime=1.17.1
  - opencv=4.6.0
  - openh264=2.3.1
  - openjpeg=2.4.0
  - openssl=3.1.7
  - orc=1.7.4
  - orjson=3.10.7
  - p11-kit=0.24.1
  - packaging=24.1
  - pandas=2.2.2
  - partd=1.4.1
  - pcre2=10.42
  - pillow=10.4.0
  - pip=24.3.1
  - pixman=0.40.0
  - prettytable=3.5.0
  - protobuf=3.20.3
  - psutil=5.9.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - py-opencv=4.6.0
  - pyarrow=14.0.2
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pydub=0.25.1
  - pygments=2.15.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.9.0post0
  - python-flatbuffers=24.3.25
  - python-multipart=0.0.9
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - python_abi=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywavelets=1.7.0
  - pyyaml=6.0.2
  - qt-main=5.15.6
  - qudida=0.0.4
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.9.11
  - requests=2.32.3
  - responses=0.13.3
  - rich=13.7.1
  - rpds-py=0.10.6
  - s2n=1.3.27
  - sacremoses=0.0.43
  - safetensors=0.4.5
  - scikit-image=0.20.0
  - scikit-learn=1.5.1
  - scipy=1.14.1
  - semantic_version=2.8.5
  - setuptools=75.5.0
  - shellingham=1.5.0
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - sqlite=3.45.3
  - starlette=0.38.2
  - svt-av1=1.4.1
  - sympy=1.13.2
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tifffile=2020.6.3
  - tk=8.6.13
  - tokenizers=0.14.1
  - tomlkit=0.12.0
  - toolz=0.12.0
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tqdm=4.66.5
  - transformers=4.34.1
  - typer=0.9.0
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - utf8proc=2.6.1
  - uvicorn=0.30.6
  - wcwidth=0.2.5
  - websockets=10.4
  - wheel=0.45.0
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xxhash=0.8.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.11.0
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - asttokens==2.4.1
      - decorator==5.1.1
      - executing==2.1.0
      - ipdb==0.13.13
      - ipython==8.29.0
      - jedi==0.19.2
      - matplotlib-inline==0.1.7
      - onnxruntime-gpu==1.16.3
      - parso==0.8.4
      - peft==0.5.0
      - pexpect==4.9.0
      - prompt-toolkit==3.0.48
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - stack-data==0.6.3
      - tomli==2.1.0
      - traitlets==5.14.3
